#!/bin/bash

if [ $# != 2 ]; then
  echo "Usage: $0 system archive_dir" 1>&2
  exit 1
fi

sys=$1
archive_dir=$2

if [ ! -f ${sys}.json ]; then
    echo "ERROR: ${sys}.json file does not exist, refusing to try to archive" 1>&2
    exit 2
fi

mkdir ${archive_dir}
if [ $? != 0 ]; then
  echo "ERROR: Failed to make archive_dir '$archive_dir'" 1>&2
  exit 3
fi

mv gap_rss_*out run_iter_* run_dft_convergence_test multistage_GAP_fit_settings.json buildcell.*input ACTIVE_ITER gap_rss_${sys}_new.stderr gap_rss_iter_fit.prep.* atoms_and_dimers.xyz ${archive_dir}/
cp ${sys}.json job.gap_rss_iter_fit.${sys}.pbs ${archive_dir}/
